title: Milena Araujo
email: dev@milena.me
description: >- # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
baseurl: /mil3na/ # the subpath of your site, e.g. /blog
url: https://mil3na.github.io # the base hostname & protocol for your site, e.g. http://example.com
domain: mil3na.github.io
github_username: mil3na
# Build settings
# plugins:
#     - jekyll-feed

