title: Milena Araujo
email: dev@milena.me
baseurl: /mil3na
url: https://mil3na.github.io
domain: mil3na.github.io
github_username: mil3na
author: Milena Araujo
social:
    name: Milena Araujo
    links:
        - https://www.linkedin.com/in/mil3na/
        - https://throne.com/mln
        - https://www.instagram.com/mil3na/
        - https://500px.com/p/mln
        - https://github.com/mil3na
google_site_verification: ''
tagline: "Milena's personal and professional website"
description: >- # this means to ignore newlines until "baseurl:"
    Web Engineer, Data Explorer, and Stationery Lover
    Exploring New Horizons in Data Analysis and Data Science
# Build settings
plugins:
    - jekyll-seo-tag
